# Required imports

In [166]:
import matplotlib
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
%matplotlib inline
#%matplotlib nbagg

# Loading data

In [167]:
columns = ['x1','x2','y']
data1 = pd.read_csv("/home/user/Stackroute/p3/bin/Week6/datafile1.csv", names=columns)
data2 = pd.read_csv("/home/user/Stackroute/p3/bin/Week6/datafile2.csv", names=columns)
data3 = pd.read_csv("/home/user/Stackroute/p3/bin/Week6/datafile3.csv", names=columns)
data4 = pd.read_csv("/home/user/Stackroute/p3/bin/Week6/datafile4.csv", names=columns)

# Functions for weight computation

#### Make a prediction with weights

In [168]:
def predict_y(weights, x_train):
    activation = x_train.dot(weights)
    if activation > 0:
        return 1
    else:
        return 0

#### Estimating perceptron weights using stochastic gradient descent

In [169]:
def train(data,lrate=0.01,epochs=100):
    weights = np.random.random_sample(3)
    finalweights = []
    train_x = data.drop(['y'], axis=1)
    train_y = data['y']
    train_x[2] = 1
    train_x = np.array(train_x)
    train_y = np.array(train_y)
    for i in range(epochs):
        errorsum = 0
        for x,y in zip(train_x,train_y):
            predicted = predict_y(weights, x)
            error = y - predicted
            errorsum = errorsum + error**2
            weights = weights + x*lrate*error  
        print('Iteration=%d, Rate=%.3f, Error=%f' % (i, lrate, errorsum))
        finalweights.append(weights)
        if errorsum==0:
            print("Converged")
            break
        if i+1==epochs:
            print("Never converges")
    return weights,finalweights

# Dataset 1

In [170]:
data1.head()

x1 = input 1

x2 = input 2

y = output

#### Plotting scatter plot of the data based on perceptron output

In [171]:
plt.scatter(x=data1['x1'],y=data1['x2'],c=data1['y'])

#### Computing weights

In [172]:
weights,finalweights = train(data1,0.01,100)

In [173]:
print("x1 weight = %.5f, x2 weight = %.5f, bias = %.5f"% (weights[0],weights[1],weights[2]))

In [174]:
x = np.arange(-4,4)

In [175]:
y = -weights[0]/weights[1]*x - weights[2]/weights[1]

In [176]:
plt.plot(x,y)
plt.scatter(x=data1['x1'],y=data1['x2'],c=data1['y'])

# Dataset 2 

In [177]:
data2.head()

x1 = input 1

x2 = input 2

y = output

#### Plotting scatter plot of the data based on perceptron output

In [178]:
plt.scatter(x=data2['x1'],y=data2['x2'],c=data2['y'])

#### Computing weights

In [179]:
weights = train(data2,0.01,100)

In [180]:
print("x1 weight = %.5f, x2 weight = %.5f, bias = %.5f"% (weights[0],weights[1],weights[2]))

#### Plotting the linearly seperable line

In [181]:
x = np.arange(-3,3)
y = -weights[0]/weights[1]*x - weights[2]/weights[1]

In [182]:
plt.scatter(x=data2['x1'],y=data2['x2'],c=data2['y'])
plt.plot(x,y)

# Dataset 3

In [183]:
data3.head()

x1 = input 1

x2 = input 2

y = output

#### Plotting scatter plot of the data based on perceptron output

In [184]:
plt.scatter(x=data3['x1'],y=data3['x2'],c=data3['y'])

#### Computing weights

In [185]:
weights,finalweights = train(data3)

In [186]:
print("x1 weight = %.5f, x2 weight = %.5f, bias = %.5f"% (weights[0],weights[1],weights[2]))

# Dataset 4

In [187]:
data4.head()

x1 = input 1

x2 = input 2

y = output

#### Plotting scatter plot of the data based on perceptron output

In [188]:
plt.scatter(x=data4['x1'],y=data4['x2'],c=data4['y'])

#### Computing weights

In [189]:
weights,finalweights = train(data4,0.2,100)

In [190]:
print("x1 weight = %.5f, x2 weight = %.5f, bias = %.5f"% (weights[0],weights[1],weights[2]))

In [191]:
weights,finalweights = train(data1,0.01,100)

Iteration=0, Rate=0.010, Error=10.000000
Iteration=1, Rate=0.010, Error=9.000000
Iteration=2, Rate=0.010, Error=7.000000
Iteration=3, Rate=0.010, Error=4.000000
Iteration=4, Rate=0.010, Error=4.000000
Iteration=5, Rate=0.010, Error=4.000000
Iteration=6, Rate=0.010, Error=4.000000
Iteration=7, Rate=0.010, Error=4.000000
Iteration=8, Rate=0.010, Error=4.000000
Iteration=9, Rate=0.010, Error=3.000000
Iteration=10, Rate=0.010, Error=2.000000
Iteration=11, Rate=0.010, Error=2.000000
Iteration=12, Rate=0.010, Error=2.000000
Iteration=13, Rate=0.010, Error=2.000000
Iteration=14, Rate=0.010, Error=2.000000
Iteration=15, Rate=0.010, Error=2.000000
Iteration=16, Rate=0.010, Error=1.000000
Iteration=17, Rate=0.010, Error=1.000000
Iteration=18, Rate=0.010, Error=1.000000
Iteration=19, Rate=0.010, Error=1.000000
Iteration=20, Rate=0.010, Error=1.000000
Iteration=21, Rate=0.010, Error=1.000000
Iteration=22, Rate=0.010, Error=1.000000
Iteration=23, Rate=0.010, Error=1.000000
Iteration=24, Rate=0.010,

In [192]:
weights

array([ 0.04836391,  0.85119359, -0.11113023])

In [193]:
finalweights

[array([ 0.67377261,  0.63940429,  0.62886977]),
 array([ 0.56968451,  0.72225852,  0.53886977]),
 array([ 0.47232708,  0.78374336,  0.46886977]),
 array([ 0.42345708,  0.79681499,  0.42886977]),
 array([ 0.37458708,  0.80988661,  0.38886977]),
 array([ 0.32571709,  0.82295823,  0.34886977]),
 array([ 0.27684709,  0.83602986,  0.30886977]),
 array([ 0.22797709,  0.84910148,  0.26886977]),
 array([ 0.17910709,  0.86217311,  0.22886977]),
 array([ 0.14644092,  0.86834361,  0.19886977]),
 array([ 0.13049649,  0.86916775,  0.17886977]),
 array([ 0.11455206,  0.8699919 ,  0.15886977]),
 array([ 0.09860763,  0.87081604,  0.13886977]),
 array([ 0.0826632 ,  0.87164019,  0.11886977]),
 array([ 0.06671877,  0.87246434,  0.09886977]),
 array([ 0.05077433,  0.87328848,  0.07886977]),
 array([ 0.04343978,  0.87243005,  0.06886977]),
 array([ 0.03610523,  0.87157161,  0.05886977]),
 array([ 0.02877068,  0.87071317,  0.04886977]),
 array([ 0.02143612,  0.86985474,  0.03886977]),
 array([ 0.01410157,

In [194]:
x = np.arange(-3,3)
y = -weights[0]/weights[1]*x - weights[2]/weights[1]

In [195]:
x = [min(x1),max(x1)]
x

[-1.21073265071727, 1.9951545931474184]

In [196]:
for w in finalweights:
    ycomp = -((w[0]/w[1])*x - (w[2]/w[1]))
    print(ycomp)

x

TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [197]:
# First set up the figure, the axis, and the plot element we want to animate
%matplotlib nbagg
fig = plt.figure()
y = []
ax = plt.axes(xlim=(-2, 2), ylim=(-2, 2))
line = ax.plot([], [], lw=2)
x1 = data1['x1']
x2 = data1['x2']
y1 = data1['y']
w = np.array(finalweights)
plt.scatter(x1, x2, c=y1)
x = [min(x1),max(x1)]

for w in finalweights:
    ycomp = -((w[0]/w[1])*x - (w[2]/w[1]))
    y.append(ycomp)

# initialization function: plot the background of each frame
def init():
    line.set_data(x, -((w[0][0]//w[0][1])*x - (w[0][2]//w[0][1])))
    return line,

# animation function.  This is called sequentially
def animate(i):
   # y = -((w[i][0]/w[i][1])*x - (w[i][2]/w[i][1]))
    line.set_ydata(y)
    return line,

# call the animator.  blit=True means only re-draw the parts that have changed.
anim = animation.FuncAnimation(fig, animate, init_func=init,
                                interval=20, blit=True, repeat=False)

plt.xlabel('X1')
plt.ylabel('X2')
plt.legend(['hyperline','y=0','y=1'])
plt.title('x1 vs x2')
plt.show()

<IPython.core.display.Javascript object>

TypeError: 'numpy.float64' object cannot be interpreted as an integer